{
 "title": "Coches",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Modelo",
    "query": "SELECT DISTINCT MODEL FROM ElectricCar"
   }
  ]
 },
 "panels": [
  { "title": "Autonomía", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Autonomía en h",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  NOW() AS \"time\", \n  CONCAT(BRAND, \" \", MODEL) AS metric,\n  RANGE_KM AS value \nFROM ElectricCar \nWHERE MODEL IN ($Modelo)\nORDER BY value"
    }
   ]
  },
  {
   "title": "Autonomía en h (top 10)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  NOW() AS \"time\", \n  CONCAT(BRAND, \" \", MODEL) AS metric, \n  RANGE_KM as value \nFROM ElectricCar \nORDER BY value DESC\nLIMIT 10\n"
    }
   ]
  },
  { "title": "Eficiencia", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Eficiencia del coche en Wh/km ",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  NOW() AS \"time\", \n  CONCAT(BRAND, \" \", MODEL) AS metric, \n  EFFICIENCY_WHKM as value \nFROM ElectricCar \nWHERE MODEL IN ($Modelo)\n"
    }
   ]
  },
  {
   "title": "Eficiencia del coche en Wh/km (top 10)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  NOW() AS \"time\", \n  CONCAT(BRAND, \" \", MODEL) AS metric, \n  EFFICIENCY_WHKM as value \nFROM ElectricCar \nORDER BY value DESC\nLIMIT 10\n"
    }
   ]
  },
  { "title": "Capacidad ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Capacidad de la batería en KWh ",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  NOW() AS \"time\", \n  CONCAT(BRAND, \" \", MODEL) AS metric,\n  BATTERY_CAPACITY AS value \nFROM ElectricCar \nWHERE MODEL IN ($Modelo)\nORDER BY value"
    }
   ]
  },
  {
   "title": "Capacidad de la batería en KWh (top 10)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  NOW() AS \"time\", \n  CONCAT(BRAND, \" \", MODEL) AS metric, \n  BATTERY_CAPACITY as value \nFROM ElectricCar \nORDER BY value DESC\nLIMIT 10\n"
    }
   ]
  },
  {
   "title": "Tiempo de recarga en h con potencia de punto de recarga de 40 KW",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() as time, \n  AVG (BATTERY_CAPACITY/40) as value,\n  BRAND as metric\nFROM ElectricCar\nGROUP BY BRAND\nORDER BY value DESC\nLIMIT 10"
    }
   ]
  }
 ]
}