{
 "title": "Maps",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Charging Stations",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  id AS indice,\n  latitude AS latitude,\n  longitude AS longitude,\n  status AS status\nFROM PuntosCarga"
    }
   ]
  },
  {
   "title": "Service stations proposed as charging stations",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  id AS indice,\n  latitud AS latitude,\n  longitud AS longitude,\n  status AS status\nFROM GasolinerasPropuesta"
    }
   ]
  },
  {
   "title": "Origin and Destination",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 15 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  id AS indice,\n  latitude AS latitude,\n  longitude AS longitude,\n  status AS status\nFROM Ciudades"
    }
   ]
  },
  {
   "title": "Combined Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 15 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  id AS indice,\n  latitude AS latitude,\n  longitude AS longitude,\n  status AS status\nFROM PuntosCarga\nunion\nSELECT\n  id AS indice,\n  latitud AS latitude,\n  longitud AS longitude,\n  status AS status\nFROM GasolinerasPropuesta\nunion\nSELECT\n  id AS indice,\n  latitude AS latitude,\n  longitude AS longitude,\n  status AS status\nFROM Ciudades"
    }
   ]
  }
 ]
}