{
 "title": "Puntos de Recarga",
 "time": { "from": "2021-02-08T16:13:18.795Z", "to": "2021-02-16T16:13:18.795Z" },
 "templating": {
  "list": [
   {
    "name": "Provincia",
    "query": "SELECT DISTINCT provincia FROM PuntosCarga"
   },
   {
    "name": "Conector",
    "query": "SELECT DISTINCT REPLACE(SUBSTRING_INDEX(SUBSTRING(REPLACE(connectorType, '[', ''), 1, length(connectorType)),',',character_length(',')) ,'''','')\nFROM PuntosCarga;"
   }
  ]
 },
 "panels": [
  {
   "title": "Número Puntos Recarga por Provincia",
   "type": "stat",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() as \"time\",\n  provincia as metric,\n  COUNT(*) as value\nFROM PuntosCarga\nWHERE provincia IN ($Provincia)\nGROUP BY provincia"
    }
   ]
  },
  {
   "title": "Informacion Puntos de Recarga",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  id,\n  provincia as Provincia,\n  ccaa as \"Comunidad Autonoma\",\n  connectorType as \"Tipo conector\",\n  ratedPowerKW as Potencia\nFROM PuntosCarga\nWHERE provincia IN ($Provincia)"
    }
   ]
  },
  {
   "title": "Número de conectores",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 18, "w": 10, "x": 0, "y": 11 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  id AS id,\n  latitude AS latitude,\n  longitude AS longitude,\n  num_connectors AS metric\nFROM PuntosCarga"
    }
   ]
  },
  {
   "title": "Potencia para conector $Conector [kW]",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 18, "w": 10, "x": 10, "y": 11 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  id AS id,\n  latitude AS latitude,\n  longitude AS longitude,\n  ratedPowerKW AS metric\nFROM PuntosCarga\nWHERE connectorType LIKE ($Conector)"
    }
   ]
  }
 ]
}