version: "3.4"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - monitoring
    environment:
      plugins: "grafana-worldmap-panel"
    restart: always
  db:
    image: mysql:latest
    container_name: monitoring_db
    ports:
      - 3306:3306
    networks:
      - monitoring
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: tfm
      MYSQL_PASSWORD: Tfmmaster1
networks:
  monitoring:
    external: true
volumes:
  grafana-data:
    external: true
