CREATE TABLE IF NOT EXISTS LOG_IN_USUARIOS (
    NOMBRE VARCHAR(255) NOT NULL ,
    APELLIDO VARCHAR(255) NOT NULL,
    CORREO VARCHAR(255) NOT NULL PRIMARY KEY,
    CONTRASEÑA VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ;

SELECT * FROM USUARIOS;

CREATE TABLE IF NOT EXISTS INFO_USUARIOS (
     VARCHAR(255) NOT NULL ,
    APELLIDO VARCHAR(255) NOT NULL,
    TYPE_CAR VARCHAR(255) NOT NULL PRIMARY KEY,
    CONTRASEÑA VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ;